[package]
name = "nonces"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.8.1"
crypto-bigint = "0.6.1"
hex = "0.4.3"
hex-literal = "1.1.0"

[[bench]]
name = "bencher"
harness = false
